version: 2
jobs:
  build:
    working_directory: ~/example-foobar
    docker:
      - image: ruby:2.4
        environment:
          CODECLIMATE_REPO_TOKEN: "f3f56f0ce88e7483ed9c1562d75b37e53b6777e92e930bed1c2151b0c7c64269"
    steps:
      - checkout
      - type: cache-restore
        key: example-foobar-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: example-foobar-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec rspec && bundle exec codeclimate-test-reporter
